"use client";

import { useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Breadcrumb } from "@/components/ui/breadcrumb";
import { ArrowRight, Check, ChevronDown, ShieldCheck, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";

/* -------------------------------------------------------------------------- */
/*  Hero                                                                      */
/* -------------------------------------------------------------------------- */
function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div className="container mx-auto max-w-4xl px-4 py-12 md:py-20">
        <Breadcrumb
          items={[
            { label: "Home", href: "/" },
            { label: "Free AI Headshot Generator" },
          ]}
          className="mb-6"
        />
        <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-muted/50 px-4 py-1.5 text-base text-muted-foreground">
          <Sparkles className="h-4 w-4 text-primary" />
          No credit card required
        </div>
        <h1 className="text-balance text-4xl font-bold leading-tight tracking-tight md:text-5xl lg:text-6xl">
          Free AI Headshot Generator — Try Free, No Credit Card
        </h1>
        <p className="mt-6 text-balance text-lg text-muted-foreground md:text-xl max-w-2xl">
          Get a professional AI-generated headshot for free. Upload 1 selfie,
          get a studio-quality portrait in under 5 minutes — no credit card,
          no watermark, no catch. Upgrade to Starter or Pro when you want more.
        </p>
        <div className="mt-8 flex flex-col items-start gap-4 sm:flex-row sm:items-center">
          <Link href="/generate?free=true">
            <Button size="lg" className="h-12 px-8 text-base">
              Try free
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </Link>
          <div className="flex items-center gap-2 text-base text-muted-foreground">
            <ShieldCheck className="h-4 w-4 text-green-500" />
            1 free headshot · Instant preview
          </div>
        </div>
      </div>
      <div className="pointer-events-none absolute inset-0 -z-10">
        <div className="absolute top-1/4 left-1/2 -translate-x-1/2 h-96 w-96 rounded-full bg-primary/10 blur-3xl" />
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  What You Get for Free                                                     */
/* -------------------------------------------------------------------------- */
const FREE_FEATURES = [
  {
    title: "1 professional headshot",
    body: "A full-resolution, studio-quality headshot generated by FLUX.2 pro — the same model powering our paid Starter plan. No tiny thumbnail, no pixelation.",
  },
  {
    title: "Natural style",
    body: "Clean, professional look with natural lighting. Perfect for LinkedIn, your company website, email signature, or any professional context.",
  },
  {
    title: "Under 5 minutes",
    body: "Upload your selfie, and our AI delivers your free headshot in under 5 minutes. No waiting days for editing — instant, automated, professional.",
  },
  {
    title: "No credit card · No watermark",
    body: "Genuinely free. We don't ask for payment info. We don't slap a watermark across your photo. We don't trick you into a subscription. Try it, see the quality, upgrade only if you want to.",
  },
];

function WhatYouGet() {
  return (
    <section className="border-t border-border">
      <div className="container mx-auto max-w-4xl px-4 py-12 md:py-20">
        <h2 className="text-3xl font-bold tracking-tight text-center">
          What you get — genuinely free
        </h2>
        <p className="mt-4 text-center text-lg text-muted-foreground max-w-2xl mx-auto">
          Most "free" AI headshot tools aren't actually free. Here's what
          TryOneTake gives you — no asterisks, no fine print.
        </p>
        <div className="mt-8 grid gap-5 sm:grid-cols-2">
          {FREE_FEATURES.map((f) => (
            <div
              key={f.title}
              className="rounded-xl border border-border bg-card p-6"
            >
              <Check className="h-5 w-5 text-green-500 mb-3" />
              <h3 className="font-semibold text-lg">{f.title}</h3>
              <p className="mt-2 text-base text-muted-foreground leading-relaxed">
                {f.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  How It Works                                                               */
/* -------------------------------------------------------------------------- */
const STEPS = [
  {
    step: "1",
    title: "Create a free account",
    body: "Sign up with Google or email in seconds. No payment info required — we never ask for your credit card for the free tier.",
  },
  {
    step: "2",
    title: "Upload 1 selfie",
    body: "Take a well-lit selfie with your phone — natural window light, plain background, looking at the lens. One good photo is all our AI needs.",
  },
  {
    step: "3",
    title: "Get your free headshot",
    body: "Our FLUX.2 pro AI generates your professional headshot in under 5 minutes. Download it instantly — full resolution, no watermark, genuinely free.",
  },
];

function HowItWorks() {
  return (
    <section className="border-t border-border bg-muted/30">
      <div className="container mx-auto max-w-4xl px-4 py-12 md:py-20">
        <h2 className="text-3xl font-bold tracking-tight text-center">
          How to get your free AI headshot
        </h2>
        <p className="mt-4 text-center text-lg text-muted-foreground">
          Three steps. Zero dollars. Five minutes.
        </p>
        <div className="mt-8 grid gap-6 md:grid-cols-3">
          {STEPS.map((s) => (
            <div
              key={s.step}
              className="relative rounded-xl border border-border bg-card p-6"
            >
              <div className="mb-4 flex h-10 w-10 items-center justify-center rounded-full bg-primary/10 text-lg font-bold text-primary">
                {s.step}
              </div>
              <h3 className="font-semibold text-lg">{s.title}</h3>
              <p className="mt-2 text-base text-muted-foreground leading-relaxed">
                {s.body}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  "Free" vs Actually Free                                                   */
/* -------------------------------------------------------------------------- */
const COMPARISON_ROWS = [
  {
    label: "Credit card required",
    tryonetake: "No",
    tryonetakeGood: true,
    others: "Usually yes — auto-charge after trial",
  },
  {
    label: "Watermark on free output",
    tryonetake: "Never",
    tryonetakeGood: true,
    others: "Often — large logo overlay",
  },
  {
    label: "Free output resolution",
    tryonetake: "Full resolution (1024×1024+)",
    tryonetakeGood: true,
    others: "Often reduced to 256×256 thumbnail",
  },
  {
    label: "Photos required",
    tryonetake: "1 photo",
    tryonetakeGood: true,
    others: "10–20 photos often required",
  },
  {
    label: "Free headshots per user",
    tryonetake: "1 (try quality before buying)",
    tryonetakeGood: false,
    others: "1–3 (but often unusable quality)",
  },
  {
    label: "Upgrade path",
    tryonetake: "$19 one-time (30 headshots, 10 styles)",
    tryonetakeGood: true,
    others: "Often subscription ($10–$30/month)",
  },
];

function TheTruth() {
  return (
    <section className="border-t border-border">
      <div className="container mx-auto max-w-4xl px-4 py-12 md:py-20">
        <h2 className="text-3xl font-bold tracking-tight text-center">
          Why most "free AI headshot generators" aren't really free
        </h2>
        <p className="mt-4 text-center text-lg text-muted-foreground max-w-2xl mx-auto">
          Many competitors advertise "free" but hide the real story behind
          credit card walls, watermarks, and tiny thumbnails. Here's how
          TryOneTake compares.
        </p>
        <div className="mt-8 overflow-x-auto rounded-xl border border-border">
          <table className="w-full min-w-[600px] text-base">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                <th className="px-6 py-4 text-left font-medium w-1/3">
                  What "free" means
                </th>
                <th className="px-6 py-4 text-left font-semibold">
                  <span className="rounded-md bg-primary/10 px-3 py-1 text-primary">
                    TryOneTake (actually free)
                  </span>
                </th>
                <th className="px-6 py-4 text-left text-muted-foreground">
                  Most competitors
                </th>
              </tr>
            </thead>
            <tbody>
              {COMPARISON_ROWS.map((row) => (
                <tr
                  key={row.label}
                  className="border-b border-border last:border-0"
                >
                  <td className="px-6 py-4 font-medium">{row.label}</td>
                  <td className="px-6 py-4">
                    <span
                      className={
                        row.tryonetakeGood
                          ? "font-semibold text-green-600"
                          : "text-foreground"
                      }
                    >
                      {row.tryonetake}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-muted-foreground">
                    {row.others}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  Free vs Paid                                                              */
/* -------------------------------------------------------------------------- */
const plans = [
  {
    name: "Free",
    price: "$0",
    model: "FLUX.2 pro",
    photos: "1 headshot",
    styles: "Natural style only",
    features: [
      "FLUX.2 pro model (same as Starter)",
      "1 professional headshot",
      "Natural style",
      "No watermark · Full resolution",
      "Instant delivery",
      "Upgrade to Starter or Pro anytime",
    ],
    cta: "Start free",
    href: "/generate?free=true",
    featured: false,
  },
  {
    name: "Starter",
    price: "$19",
    model: "FLUX.2 pro",
    photos: "30 headshots",
    styles: "10 style variations",
    features: [
      "FLUX.2 pro model",
      "30 professional headshots",
      "10 style variations",
      "Balanced / Natural / Polished",
      "No watermark · Full resolution",
      "Instant download (ZIP)",
      "Automatic refund if generation fails",
    ],
    cta: "Get Starter",
    href: "/generate?plan=starter",
    featured: false,
  },
  {
    name: "Pro",
    price: "$35",
    model: "FLUX.2 max",
    photos: "30 headshots",
    styles: "25 style variations",
    features: [
      "FLUX.2 max model (highest realism)",
      "30 professional headshots",
      "25 style variations",
      "Balanced / Natural / Polished",
      "No watermark · Full resolution",
      "Instant download (ZIP)",
      "Automatic refund if generation fails",
    ],
    cta: "Get Pro",
    href: "/generate?plan=pro",
    featured: true,
  },
];

function FreeVsPaid() {
  return (
    <section className="border-t border-border bg-muted/30">
      <div className="container mx-auto max-w-6xl px-4 py-12 md:py-20">
        <h2 className="text-3xl font-bold tracking-tight text-center">
          Free vs paid: what&apos;s the difference?
        </h2>
        <p className="mt-4 text-center text-lg text-muted-foreground">
          Try free. When you need more than one headshot, upgrade to a paid plan
          — one-time payment, no subscription.
        </p>
        <div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {plans.map((plan) => (
            <div
              key={plan.name}
              className={`relative flex flex-col rounded-2xl border p-6 transition-shadow hover:shadow-lg ${
                plan.featured
                  ? "border-primary/50 bg-card shadow-md ring-1 ring-primary/20"
                  : "border-border bg-card"
              }`}
            >
              {plan.featured && (
                <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1 text-sm font-semibold text-primary-foreground">
                  Most Popular
                </div>
              )}
              <div className="mb-6">
                <h3 className="text-xl font-semibold">{plan.name}</h3>
                <div className="mt-2 flex items-baseline gap-1">
                  <span className="text-4xl font-bold">{plan.price}</span>
                  {plan.price !== "$0" && (
                    <span className="text-muted-foreground text-sm">
                      one-time
                    </span>
                  )}
                </div>
                <div className="mt-3 flex flex-wrap gap-2 text-sm text-muted-foreground">
                  <span className="rounded-md bg-muted px-2 py-0.5">
                    {plan.model}
                  </span>
                  <span className="rounded-md bg-muted px-2 py-0.5">
                    {plan.photos}
                  </span>
                  <span className="rounded-md bg-muted px-2 py-0.5">
                    {plan.styles}
                  </span>
                </div>
              </div>
              <ul className="mb-8 flex-1 space-y-3 text-base">
                {plan.features.map((f) => (
                  <li key={f} className="flex items-start gap-2">
                    <Check className="mt-0.5 h-4 w-4 shrink-0 text-green-500" />
                    <span className="text-muted-foreground">{f}</span>
                  </li>
                ))}
              </ul>
              <Link href={plan.href} className="block">
                <Button
                  variant={plan.featured ? "default" : "outline"}
                  className="w-full"
                >
                  {plan.cta}
                  <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </Link>
            </div>
          ))}
        </div>
        <p className="mt-6 text-center text-sm text-muted-foreground">
          All plans: one-time payment. No subscription.{" "}
          <Link
            href="/refund"
            className="text-primary underline underline-offset-2 font-medium"
          >
            Automatic refund if generation fails →
          </Link>
        </p>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  Why We Offer It Free                                                      */
/* -------------------------------------------------------------------------- */
function WhyFree() {
  return (
    <section className="border-t border-border">
      <div className="container mx-auto max-w-3xl px-4 py-12 md:py-20 text-center">
        <h2 className="text-3xl font-bold tracking-tight">
          Why do we offer a free AI headshot?
        </h2>
        <p className="mt-6 text-lg text-muted-foreground leading-relaxed max-w-2xl mx-auto">
          Because we believe the quality speaks for itself. Most people who try
          our free headshot come back for the full set — not because we trick
          them, but because they see what FLUX.2 can do with just one selfie.
        </p>
        <p className="mt-4 text-lg text-muted-foreground leading-relaxed max-w-2xl mx-auto">
          The free tier is our best marketing. No ads, no dark patterns, no
          auto-billing. Try it, see the quality, and decide for yourself whether
          the full set of 30 headshots is worth $19. We think you will.
        </p>
        <Link href="/generate?free=true" className="mt-6 inline-block">
          <Button size="lg" variant="outline" className="h-12 px-8 text-base">
            Try free
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </Link>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  FAQ                                                                       */
/* -------------------------------------------------------------------------- */
const FREETOOL_FAQS = [
  {
    q: "Is this AI headshot generator really free?",
    a: "Yes — genuinely free. TryOneTake's free tier gives you 1 professional headshot generated by FLUX.2 pro, the same model powering our $19 Starter plan. No credit card required, no watermark, full resolution, instant delivery. We offer it free because we're confident you'll love the quality and want the full set of 30 — but there's zero obligation to upgrade.",
  },
  {
    q: "Do I need a credit card to try the free AI headshot generator?",
    a: "No. TryOneTake's free tier requires no payment information whatsoever. Sign up with Google or email, upload 1 selfie, and get your free headshot. Many competitors require a credit card and auto-charge you after a trial period — we don't.",
  },
  {
    q: "What's the catch? Why is it free?",
    a: "There's no catch. The free tier exists because (a) it's our most effective marketing — people try it, love the quality, and voluntarily upgrade to Starter or Pro, and (b) it costs us very little to generate a single headshot. The 1-free-per-user limit ensures the economics work. Think of it as a free sample — try before you buy, genuinely.",
  },
  {
    q: "How many free headshots can I generate?",
    a: "One free headshot per user. This lets you test the quality and see how well our AI preserves your identity. If you want more (30 headshots with 10–25 style variations), upgrade to Starter ($19 one-time) or Pro ($35 one-time). The limit ensures we can sustainably offer a genuinely free tier.",
  },
  {
    q: "What's the difference between the free and paid AI headshots?",
    a: "The free tier uses FLUX.2 pro — the same model as our $19 Starter plan. The difference is quantity and variety: free gives you 1 headshot in Natural style; Starter gives you 30 headshots across 10 style variations; Pro uses the higher-end FLUX.2 max model with 25 style variations. Quality-wise, the free headshot is identical to a Starter headshot.",
  },
  {
    q: "How does TryOneTake compare to other free AI headshot generators?",
    a: "Most 'free' AI headshot generators fall into three traps: (1) require a credit card and auto-bill after a trial, (2) deliver watermarked, low-resolution thumbnails that are unusable, or (3) require 10–20 photos before generating anything. TryOneTake is different: 1 photo, genuinely free, no watermark, full resolution, no credit card. See our comparison table above for the full breakdown.",
  },
  {
    q: "Can I really use the free headshot on LinkedIn?",
    a: "Yes. The free headshot is a full-resolution, professional-quality photo — perfectly suitable for LinkedIn, your company website, email signature, or anywhere you need a professional photo. It's the same quality as our paid headshots. No watermark, no 'free tier' downgrade.",
  },
  {
    q: "What if I don't like my free headshot?",
    a: "Since it's free, there's nothing to lose. If the result doesn't meet your expectations, you haven't paid anything and you haven't given us your credit card. You can try uploading a different selfie (better lighting, plainer background) or simply walk away. If you upgrade to a paid plan and the generation fails, our automatic refund policy has you covered.",
  },
];

function FreeHeadshotFaq() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  return (
    <section className="border-t border-border bg-muted/30">
      <div className="container mx-auto max-w-3xl px-4 py-12 md:py-20">
        <h2 className="text-3xl font-bold tracking-tight text-center">
          Frequently asked questions about free AI headshots
        </h2>
        <div className="mt-8 divide-y divide-border">
          {FREETOOL_FAQS.map((faq, i) => (
            <div key={i} className="py-5">
              <button
                onClick={() => setOpenIndex(openIndex === i ? null : i)}
                className="flex w-full items-center justify-between text-left"
              >
                <span className="pr-4 text-base font-medium">{faq.q}</span>
                <ChevronDown
                  className={cn(
                    "h-5 w-5 shrink-0 text-muted-foreground transition-transform",
                    openIndex === i && "rotate-180"
                  )}
                />
              </button>
              <div
                className={cn(
                  "grid transition-all",
                  openIndex === i
                    ? "grid-rows-[1fr] opacity-100"
                    : "grid-rows-[0fr] opacity-0"
                )}
              >
                <div className="overflow-hidden">
                  <p className="pt-3 text-base text-muted-foreground leading-relaxed">
                    {faq.a}
                  </p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  Bottom CTA                                                                 */
/* -------------------------------------------------------------------------- */
function BottomCta() {
  return (
    <section className="border-t border-border">
      <div className="container mx-auto max-w-3xl px-4 py-12 md:py-20 text-center">
        <h2 className="text-3xl font-bold tracking-tight">
          Ready to try the best free AI headshot generator?
        </h2>
        <p className="mt-4 text-lg text-muted-foreground">
          Upload 1 selfie. Get a free professional headshot in under 5 minutes.
          No credit card, no watermark, no catch.
        </p>
        <Link href="/generate?free=true" className="mt-6 inline-block">
          <Button size="lg" className="h-12 px-8 text-base">
            Try free
            <ArrowRight className="ml-2 h-4 w-4" />
          </Button>
        </Link>
        <p className="mt-4 text-sm text-muted-foreground">
          Want the full set?{" "}
          <Link
            href="/#pricing"
            className="text-primary underline underline-offset-2 font-medium"
          >
            See Starter & Pro plans →
          </Link>
        </p>
      </div>
    </section>
  );
}

/* -------------------------------------------------------------------------- */
/*  Main Page                                                                  */
/* -------------------------------------------------------------------------- */
const siteUrl = "https://tryonetake.com";

export function FreeHeadshotPage() {
  return (
    <>
      {/* JSON-LD: BreadcrumbList */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "BreadcrumbList",
            itemListElement: [
              { "@type": "ListItem", position: 1, name: "Home", item: siteUrl },
              {
                "@type": "ListItem",
                position: 2,
                name: "Free AI Headshot Generator",
                item: `${siteUrl}/free-ai-headshot-generator`,
              },
            ],
          }),
        }}
      />
      {/* JSON-LD: FAQPage */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "FAQPage",
            mainEntity: FREETOOL_FAQS.map((faq) => ({
              "@type": "Question",
              name: faq.q,
              acceptedAnswer: {
                "@type": "Answer",
                text: faq.a,
              },
            })),
          }),
        }}
      />

      <Hero />
      <WhatYouGet />
      <HowItWorks />
      <TheTruth />
      <FreeVsPaid />
      <WhyFree />
      <FreeHeadshotFaq />
      <BottomCta />
    </>
  );
}
