import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "OneTake terms of service — acceptable use, AI-generated results policy, refunds, and liability limitations.",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto max-w-2xl px-4 py-16">
      <Link href="/" className="text-sm text-muted-foreground hover:text-foreground">
        ← Back to home
      </Link>
      <h1 className="mt-6 text-3xl font-bold">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">Last updated: July 2026</p>

      <div className="mt-8 space-y-8 text-base leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold">1. Service Description</h2>
          <p className="mt-2 text-muted-foreground">
            OneTake provides AI-generated professional headshots using the FLUX.2 model
            family. You upload photos of yourself, and we generate a set of headshot
            variations. This is a one-time purchase — no subscriptions, no recurring charges.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">2. Acceptable Use</h2>
          <p className="mt-2 text-muted-foreground">
            You agree to upload only photos of yourself. You may not upload photos of
            other people without their explicit consent. You may not use OneTake to
            generate misleading, fraudulent, or inappropriate content.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">3. AI-Generated Results</h2>
          <p className="mt-2 text-muted-foreground">
            Results are generated by AI and may vary based on input photo quality. While
            we strive for high accuracy, we cannot guarantee that every generated headshot
            will perfectly match your expectations. Uploading high-quality, well-lit photos
            following our guidelines produces the best results.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">4. Refund Policy</h2>
          <p className="mt-2 text-muted-foreground">
            If all 30 headshots fail to generate due to a technical issue on our side, you
            receive a full automatic refund. If only some fail, you receive a pro-rata
            refund for the failed portion. Please see our{" "}
            <Link href="/refund" className="text-primary underline">
              Refund Policy
            </Link>{" "}
            for full details.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">5. Limitation of Liability</h2>
          <p className="mt-2 text-muted-foreground">
            OneTake is provided &ldquo;as is.&rdquo; We are not liable for any damages
            arising from the use or inability to use our service. Our maximum liability
            is limited to the amount you paid for the specific order in question.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold">6. Contact</h2>
          <p className="mt-2 text-muted-foreground">
            Questions? Contact us at{" "}
            <a href="mailto:yueheng0816@gmail.com" className="text-primary underline">
              yueheng0816@gmail.com
            </a>.
          </p>
        </section>
      </div>
    </div>
  );
}
